#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jul 17 06:07:59 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}